version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: app:mps
    container_name: mps_container
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mps_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "django-app-db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
