version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8002:8002
    image: app:djangolearn3
    container_name: djangolearn3_container
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db3
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "django-app-db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
