# Generated by Django 4.1 on 2022-08-14 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tingkataktivitas_rename_role_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tingkat_aktivitas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tingkat_aktivitas', to='base.tingkataktivitas'),
        ),
    ]
