# Generated by Django 4.1 on 2022-08-15 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_tingkat_aktivitas"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="berat_badan",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="butuh_karbo",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="butuh_lemak",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="butuh_protein",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="imt",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="keseluruhan_energi",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tinggi_badan",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="usia",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
