# Generated by Django 4.1 on 2022-08-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_avatar_user_berat_badan_user_butuh_karbo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RencanaDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="base.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Olahraga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Complete"), (2, "Incomplete")], default=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rencana_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rencana_diet_olahraga",
                        to="base.rencanadiet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Minum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_minum", models.IntegerField()),
                ("banyak_minum", models.IntegerField()),
                ("progress", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rencana_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rencana_diet_minum",
                        to="base.rencanadiet",
                    ),
                ),
            ],
        ),
    ]
