# Generated by Django 4.1 on 2022-08-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_bahanmakanan_created_at_bahanmakanan_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferensiMakanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[("FV", "FAVORIT"), ("BL", "BLOK")],
                        default="FV",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "makanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferensi_makanan",
                        to="base.makanan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferensi_user",
                        to="base.user",
                    ),
                ),
            ],
        ),
    ]
