# Generated by Django 4.1 on 2022-08-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_preferensimakanan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakananDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waktu_makan",
                    models.CharField(
                        choices=[
                            ("PH", "PAGI"),
                            ("SI", "SIANG"),
                            ("ML", "MALAM"),
                            ("CA", "CAMILAN"),
                        ],
                        default="PH",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Complete"), (2, "Incomplete")], default=2
                    ),
                ),
                (
                    "makanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rencana_makanan",
                        to="base.makanan",
                    ),
                ),
                (
                    "rencana_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rencana_diet_makanan",
                        to="base.rencanadiet",
                    ),
                ),
            ],
        ),
    ]
