# Generated by Django 4.1 on 2022-08-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_makanandiet"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiwayatRekomendasiRencanaDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("berat_badan", models.FloatField(null=True)),
                ("tinggi_badan", models.FloatField(null=True)),
                ("usia", models.IntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("PE", "PEREMPUAN"), ("LA", "LAKI")],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("imt", models.FloatField(null=True)),
                ("keseluruhan_energi", models.FloatField(null=True)),
                ("butuh_protein", models.FloatField(null=True)),
                ("butuh_karbo", models.FloatField(null=True)),
                ("butuh_lemak", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riwayat_rekomendasi_user",
                        to="base.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RekomendasiRencanaDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "riwayat_rekomendasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riwayat_rekomendasi_rencana_diet",
                        to="base.riwayatrekomendasirencanadiet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RekomendasiMakananDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waktu_makan",
                    models.CharField(
                        choices=[
                            ("PH", "PAGI"),
                            ("SI", "SIANG"),
                            ("ML", "MALAM"),
                            ("CA", "CAMILAN"),
                        ],
                        default="PH",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "makanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekomendasi_makanan",
                        to="base.makanan",
                    ),
                ),
                (
                    "rekomendasi_rencana_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekomendasi_rencana_diet",
                        to="base.rekomendasirencanadiet",
                    ),
                ),
            ],
        ),
    ]
