# Generated by Django 4.1 on 2022-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_satuan_makanan_berat_porsi_makanan_sumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satuan",
            name="nama",
            field=models.CharField(max_length=100),
        ),
    ]
