# Generated by Django 4.1 on 2022-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_satuan_nama"),
    ]

    operations = [
        migrations.AddField(
            model_name="makanan",
            name="kelompok",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
