# Generated by Django 4.1 on 2022-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_makanan_kelompok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makanan",
            name="nama",
            field=models.CharField(max_length=200),
        ),
    ]
