# Generated by Django 4.1 on 2022-08-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_makanan_nama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makanan",
            name="sumber",
            field=models.TextField(null=True),
        ),
    ]
