# Generated by Django 4.1 on 2022-08-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_makanan_sumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bahanmakanan",
            name="berat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="makanan",
            name="berat_porsi",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="makanan",
            name="energi",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="makanan",
            name="karbo",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="makanan",
            name="lemak",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="makanan",
            name="protein",
            field=models.FloatField(),
        ),
    ]
