# Generated by Django 4.1 on 2022-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_tingkataktivitas_nilai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riwayatrekomendasirencanadiet",
            name="butuh_karbo",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="riwayatrekomendasirencanadiet",
            name="butuh_lemak",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="riwayatrekomendasirencanadiet",
            name="butuh_protein",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="butuh_karbo",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="butuh_lemak",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="butuh_protein",
            field=models.JSONField(null=True),
        ),
    ]
