# Generated by Django 4.1 on 2022-10-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_riwayatrekomendasirencanadiet_butuh_karbo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="olahraga",
            name="rencana_diet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="base.rencanadiet"
            ),
        ),
    ]
