# Generated by Django 4.1 on 2022-10-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_olahraga_rencana_diet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minum",
            name="rencana_diet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="base.rencanadiet"
            ),
        ),
    ]
