# Generated by Django 4.1 on 2022-11-28 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_minum_rencana_diet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rencanadiet",
            name="tanggal",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
