# Generated by Django 4.1 on 2022-11-29 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_rencanadiet_tanggal"),
    ]

    operations = [
        migrations.AddField(
            model_name="makanandiet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="makanandiet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
